version: "3.4"
services:
  bck_service:
    env_file:
      - .env
    build: .
    networks:
      - letztalk_network
    volumes:
      - backup_vol:/usr/files

volumes:
  backup_vol:

networks:
  letztalk_network:
    driver: overlay
    attachable: true
    external: true

