#!/bin/sh
mkdir -p /etc/crontabs
echo "$CRON_EXPRESSION root env KEEP_OLD_FILES_DAYS=$KEEP_OLD_FILES_DAYS KEEP_OLD_FILES_MINUTES=$KEEP_OLD_FILES_MINUTES MONGO_HOST=$MONGO_HOST MONGO_PORT=$MONGO_PORT MONGO_USER=$MONGO_USER MONGO_PASSWORD=$MONGO_PASSWORD AUTH_DB=$AUTH_DB ACCESS_KEY_ID=$ACCESS_KEY_ID SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY ENDPOINT=$ENDPOINT BUCKET_NAME=$BUCKET_NAME DEFAULT_REGION=$DEFAULT_REGION BUCKET_PATH=$BUCKET_PATH HEALTHCHECK_IO_CHECK_URL=$HEALTHCHECK_IO_CHECK_URL bash /usr/local/bin/awesomescript.sh >> /tmp/cron_output 2>&1" > /etc/crontabs/root
chmod 0644 /etc/crontabs/root
echo "Cron job installed: $(cat /etc/crontabs/root)"
cron -L 8 -f